-- Event-creator registration questions and per-registrant answers.

create table if not exists public.event_questions (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events (id) on delete cascade,
  sort_order integer not null default 0,
  prompt text not null,
  type text not null check (type in ('text', 'choice', 'yes_no')),
  options text[] null,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  constraint event_questions_choice_options check (
    type <> 'choice' or (options is not null and cardinality(options) >= 2)
  )
);

create index if not exists event_questions_event_id_sort_idx
  on public.event_questions (event_id, sort_order);

create table if not exists public.event_question_answers (
  id bigint generated by default as identity primary key,
  events_log_id bigint not null references public.events_log (id) on delete cascade,
  question_id bigint not null references public.event_questions (id) on delete cascade,
  value text not null,
  created_at timestamptz not null default now(),
  unique (events_log_id, question_id)
);

create index if not exists event_question_answers_log_idx
  on public.event_question_answers (events_log_id);

create index if not exists event_question_answers_question_idx
  on public.event_question_answers (question_id);

create or replace function public.enforce_event_question_limit()
returns trigger
language plpgsql
as $$
begin
  if (
    select count(*)::int
    from public.event_questions
    where event_id = new.event_id
  ) >= 8 then
    raise exception 'Maximum of 8 registration questions per event';
  end if;
  return new;
end;
$$;

drop trigger if exists event_questions_limit on public.event_questions;
create trigger event_questions_limit
  before insert on public.event_questions
  for each row
  execute function public.enforce_event_question_limit();

alter table public.event_questions enable row level security;
alter table public.event_question_answers enable row level security;

grant select on table public.event_questions to anon, authenticated;
grant insert, update, delete on table public.event_questions to authenticated;
grant select, insert, update, delete on table public.event_question_answers to authenticated;

drop policy if exists event_questions_select on public.event_questions;
create policy event_questions_select
  on public.event_questions
  for select
  using (true);

drop policy if exists event_questions_write on public.event_questions;
create policy event_questions_write
  on public.event_questions
  for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists event_question_answers_select on public.event_question_answers;
create policy event_question_answers_select
  on public.event_question_answers
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.events_log el
      where el.id = event_question_answers.events_log_id
        and el.user_id = auth.uid()
    )
    or exists (
      select 1
      from public.events_log el
      join public.events e on e.id = el.event_id
      join public.user_org_roles uor
        on uor.org_uuid = e.org_id
       and uor.user_uuid = auth.uid()
      where el.id = event_question_answers.events_log_id
    )
  );

drop policy if exists event_question_answers_insert on public.event_question_answers;
create policy event_question_answers_insert
  on public.event_question_answers
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.events_log el
      where el.id = event_question_answers.events_log_id
        and el.user_id = auth.uid()
    )
  );

drop policy if exists event_question_answers_update on public.event_question_answers;
create policy event_question_answers_update
  on public.event_question_answers
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.events_log el
      where el.id = event_question_answers.events_log_id
        and el.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.events_log el
      where el.id = event_question_answers.events_log_id
        and el.user_id = auth.uid()
    )
  );

comment on table public.event_questions is
  'Creator-defined questions shown on event RSVP (and walk-up check-in if unanswered).';
comment on table public.event_question_answers is
  'Answers to event_questions, keyed to the registrant events_log row.';
