name: Scheduled PR Creation

on:
  schedule:
    - cron: "0 9 * * 1" # Runs every Monday at 9:00 AM UTC

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR for weekly updates"
          title: "Weekly Updates"
          body: "This PR contains the weekly updates to the project."
          branch: "preview" # Branch to create the PR from
          base: "main" # Target branch for the PR
